#.... tags-------------------------------------
variable "company" {
  type        = string
  description = "Company name for resource tagging"
  default     = "AWS Labs"
}
variable "createdby" {
  type        = string
  description = "Created by"
  default     = "Terraform"
}
variable "project" {
  type        = string
  description = "Project name for resource tagging"
  default     = "My Project"
}
variable "environment" {
  type        = string
  description = "Environment for resource tagging"
  default     = "sandbox"
}

# AWS===========================================================================
variable "aws_region" {
  type    = string
  default = "us-east-1"
}
#security VPC...................................................................
variable "security_vpc_az_count" {
  type    = number
  default = 2
}
variable "secuirty_vpc_name" {
  type    = string
  default = "security-vpc"
}
variable "protected_vpc_names" {
  type        = list(string)
  default     = ["protected-vpc-1", "protected-vpc-2"]
  description = "name of the protected VPC"
}
variable "security_vpc_cidr" {
  type    = string
  default = "10.90.0.0/16"
}
variable "protected_vpc_cidrs" {
  type        = list(string)
  default     = ["10.91.0.0/16", "10.92.0.0/16"]
  description = "cidr block of the protected VPC"
}
variable "security_vpc_subnets_count" {
  description = "sum of public and private subnets"
  type        = number
  default     = 5
}
variable "security_vpc_public_subnet_names" {
  type    = list(string)
  default = ["wan", "ha_mgmt"]
}
variable "security_vpc_private_subnet_names" {
  type    = list(string)
  default = ["lan", "internal_lb", "gw_attach"]
}
# Protected VPCs----------------------------------------
variable "protected_vpc_az_count" {
  type        = number
  default     = 3
  description = "number of availability zones in each protected VPC"
}
variable "protected_vpc_subnet_names" {
  type        = list(string)
  default     = ["resources", "apps", "tgw-attach"]
  description = "name of the protected VPC"
}

# Transit Gateway...............................................................
variable "tgw_name" {
  type        = string
  default     = "security-tgw"
  description = "Transit Gateway with 3 VPCs generated by Terraform Security"
}
variable "tgw_amazon_side_asn" {
  type    = number
  default = 64512
}
variable "tgw_rt_name" {
  type    = string
  default = "security-tgw"
}
variable "tgw_rt_asn" {
  type    = number
  default = 64512
}
variable "transit_gateway_cidr_blocks" {
  type    = list(string)
  default = ["1.0.0.0/24"]
}

# BGP peers
variable "tgw_connect_peer_1_asn" {
  description = "ASN for the firewal primary node"
  type        = number
  default     = 64540
}
variable "tgw_connect_peer_2_asn" {
  description = "ASN for the firewal secondary node"
  type        = number
  default     = 64541
}
variable "tgw_connect_peer_1_BGP_Inside_CIDR_blocks" {
  description = "/29 subnet for BGP inside addresses for firewal primary node. It is configured on tgw-connect peer 1"
  type        = list(string)
  default     = ["169.254.120.0/29"]
}
variable "tgw_connect_peer_2_BGP_Inside_CIDR_blocks" {
  description = "/29 subnet for BGP inside addresses for firewal secondary node. It is configured on tgw-connect peer 1"
  type        = list(string)
  default     = ["169.254.102.0/29"]
}
variable "tgw_connect_peer_1_BGP_Inside_Address" {
  description = "BGP ip of the tgw-connect peer 1. It is configured on tgw-connect peer"
  type        = string
  default     = "169.254.120.2"
}
variable "tgw_connect_peer_2_BGP_Inside_Address" {
  description = "BGP ip of the tgw-connect peer 2. It is configured on tgw-connect peer"
  type        = string
  default     = "169.254.102.2"
}

# IAM roles required FGT 
variable "fortigate-iam-role" {
  type    = string
  default = "fgt-iam-role"
}
variable "fortigate-iam-role_policy" {
  type    = string
  default = "fortigate-iam-role-policy"
}
variable "fortigate-iam-instance_profile_name" {
  type    = string
  default = "fortigate-iam-instance_profile_name"
}
